apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
  namespace: nextflow-tests
spec:
  restartPolicy: Never
  containers:
    - name: debug
      image: ubuntu:24.04
      command: ["sleep", "3600"]
      volumeMounts:
        - name: workdir
          mountPath: /workspace
  volumes:
    - name: workdir
      persistentVolumeClaim:
        claimName: nextflow-workdir
